# config/application.yml
defaults: &defaults
  pagination:
    places_per_page: 10

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  aliyun_foci_ip: http://42.96.137.114:1234